export const HomeObjOne = {
    id: "About",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "Premium Bank",
    heading: "Unlimited Transactions with Zero Fees",
    description: "Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.",
    buttonLable: "Get Started",
    imgStart: false,
    img: require("../Images/IMG1.svg").default,
    alt: "Car",
    dark: true,
    primary: true,
    darkText: false,
};

export const HomeObjTwo = {
    id: "Discover",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Unlimited Access",
    heading: "Log into you Account at any time",
    description: "We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.",
    buttonLable: "Learn More",
    imgStart: true,
    img: require("../Images/IMG4.svg").default,
    alt: "PiggyBank",
    dark: false,
    primary: false,
    darkText: true,
};

export const HomeObjThree = {
    id: "SignUp",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Join our Team",
    heading: "Creating an Acoount is extremely easy",
    description: "Get everything set up and ready in under 10 minutes. All you need to do is add your information and you are ready to go.",
    buttonLable: "Start Now",
    imgStart: false,
    img: require("../Images/IMG2.svg").default,
    alt: "Papers",
    dark: false,
    primary: false,
    darkText: true,
};